// <auto-generated />
using System;
using BackClub.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackClub.Migrations
{
    [DbContext(typeof(InscripcionesContext))]
    partial class InscripcionesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BackClub.Models.Cuota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DeportistaId")
                        .HasColumnType("int");

                    b.Property<string>("EstadoPago")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("DeportistaId");

                    b.ToTable("cuotas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DeportistaId = 1,
                            EstadoPago = "pagado",
                            FechaPago = new DateTime(2024, 9, 15, 9, 1, 44, 897, DateTimeKind.Local).AddTicks(8064),
                            Monto = 50.00m
                        },
                        new
                        {
                            Id = 2,
                            DeportistaId = 2,
                            EstadoPago = "pendiente",
                            FechaPago = new DateTime(2024, 8, 15, 9, 1, 44, 897, DateTimeKind.Local).AddTicks(8083),
                            Monto = 50.00m
                        },
                        new
                        {
                            Id = 3,
                            DeportistaId = 3,
                            EstadoPago = "pagado",
                            FechaPago = new DateTime(2024, 9, 15, 9, 1, 44, 897, DateTimeKind.Local).AddTicks(8085),
                            Monto = 50.00m
                        });
                });

            modelBuilder.Entity("BackClub.Models.Deporte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<TimeSpan>("Hora")
                        .HasColumnType("time(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("deportes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Deporte de equipo",
                            Hora = new TimeSpan(0, 18, 0, 0, 0),
                            Nombre = "Fútbol"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Deporte de equipo",
                            Hora = new TimeSpan(0, 19, 0, 0, 0),
                            Nombre = "Basquetbol"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Deporte individual",
                            Hora = new TimeSpan(0, 17, 0, 0, 0),
                            Nombre = "Natación"
                        });
                });

            modelBuilder.Entity("BackClub.Models.Deportista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApellidoNombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("DeporteId")
                        .HasColumnType("int");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("DeporteId");

                    b.ToTable("deportistas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApellidoNombre = "Carlos López",
                            DeporteId = 1,
                            Direccion = "Calle Falsa 123",
                            Eliminado = false,
                            Email = "carlos@example.com",
                            Telefono = "321654987"
                        },
                        new
                        {
                            Id = 2,
                            ApellidoNombre = "María Fernández",
                            DeporteId = 2,
                            Direccion = "Avenida Siempre Viva 742",
                            Eliminado = false,
                            Email = "maria@example.com",
                            Telefono = "654987321"
                        },
                        new
                        {
                            Id = 3,
                            ApellidoNombre = "Pedro Sánchez",
                            DeporteId = 3,
                            Direccion = "Boulevard de los Sueños Rotos",
                            Eliminado = false,
                            Email = "pedro@example.com",
                            Telefono = "789321654"
                        });
                });

            modelBuilder.Entity("BackClub.Models.Profesor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("DeporteId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("DeporteId");

                    b.ToTable("profesores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellido = "Molina",
                            DeporteId = 1,
                            Nombre = "Marcelo",
                            Telefono = "123456789"
                        },
                        new
                        {
                            Id = 2,
                            Apellido = "Giunta",
                            DeporteId = 2,
                            Nombre = "Renzo",
                            Telefono = "987654321"
                        },
                        new
                        {
                            Id = 3,
                            Apellido = "Valiente",
                            DeporteId = 3,
                            Nombre = "Camila",
                            Telefono = "456123789"
                        });
                });

            modelBuilder.Entity("BackClub.Models.Cuota", b =>
                {
                    b.HasOne("BackClub.Models.Deportista", "Deportista")
                        .WithMany("Cuotas")
                        .HasForeignKey("DeportistaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deportista");
                });

            modelBuilder.Entity("BackClub.Models.Deportista", b =>
                {
                    b.HasOne("BackClub.Models.Deporte", "Deporte")
                        .WithMany()
                        .HasForeignKey("DeporteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deporte");
                });

            modelBuilder.Entity("BackClub.Models.Profesor", b =>
                {
                    b.HasOne("BackClub.Models.Deporte", "Deporte")
                        .WithMany("Profesores")
                        .HasForeignKey("DeporteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deporte");
                });

            modelBuilder.Entity("BackClub.Models.Deporte", b =>
                {
                    b.Navigation("Profesores");
                });

            modelBuilder.Entity("BackClub.Models.Deportista", b =>
                {
                    b.Navigation("Cuotas");
                });
#pragma warning restore 612, 618
        }
    }
}
